/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BaseModelSelect: typeof import('./src/components/design/layout/baseModelSelect/index.vue')['default']
    BottomMenu: typeof import('./src/components/design/layout/bottomMenu.vue')['default']
    Canvas: typeof import('./src/components/design/layout/customTextSticker/canvas.vue')['default']
    ColorPicker: typeof import('./src/components/design/components/colorPicker.vue')['default']
    Container: typeof import('./src/components/design/components/container.vue')['default']
    CustomTextSticker: typeof import('./src/components/design/layout/customTextSticker/index.vue')['default']
    DecalControl: typeof import('./src/components/design/layout/decalControl/index.vue')['default']
    DecalList: typeof import('./src/components/design/layout/decalList/index.vue')['default']
    Design: typeof import('./src/components/design/index.vue')['default']
    Dialog: typeof import('./src/components/design/components/dialog.vue')['default']
    Empty: typeof import('./src/components/design/layout/workspace/empty.vue')['default']
    FontList: typeof import('./src/components/design/layout/fontList/index.vue')['default']
    FontUpload: typeof import('./src/components/design/layout/fontUpload/index.vue')['default']
    GltfViewer: typeof import('./src/components/model/gltfViewer/index.vue')['default']
    HeaderMenu: typeof import('./src/components/design/layout/headerMenu.vue')['default']
    HeaderMenuDropdown: typeof import('./src/components/design/layout/headerMenuDropdown/index.vue')['default']
    ImageSticker: typeof import('./src/components/design/layout/imageSticker/index.vue')['default']
    ImageUpload: typeof import('./src/components/design/layout/imageUpload/index.vue')['default']
    LeftMenu: typeof import('./src/components/design/layout/leftMenu.vue')['default']
    Loading: typeof import('./src/components/design/layout/loading.vue')['default']
    Main: typeof import('./src/components/design/layout/main.vue')['default']
    Menu: typeof import('./src/components/design/layout/headerMenuDropdown/menu.vue')['default']
    MenuItem: typeof import('./src/components/design/layout/headerMenuDropdown/menuItem.vue')['default']
    ModelInfo: typeof import('./src/components/design/layout/modelInfo/index.vue')['default']
    OperateFormItem: typeof import('./src/components/design/layout/customTextSticker/operate/operateFormItem.vue')['default']
    Resource: typeof import('./src/components/design/layout/textSticker/resource.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SceneControl: typeof import('./src/components/design/layout/sceneControl/index.vue')['default']
    Setting: typeof import('./src/components/design/layout/setting/index.vue')['default']
    SubHeaderMenu: typeof import('./src/components/design/layout/subHeaderMenu/index.vue')['default']
    Tab: typeof import('./src/components/design/components/tab.vue')['default']
    TextSticker: typeof import('./src/components/design/layout/textSticker/index.vue')['default']
    UserAvatar: typeof import('./src/components/user/userAvatar.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanConfigProvider: typeof import('vant/es')['ConfigProvider']
    VanIcon: typeof import('vant/es')['Icon']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
    Workspace: typeof import('./src/components/design/layout/workspace/index.vue')['default']
  }
}
